---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp category.html $DEPLOYPATH
    - /bin/cp contact_us.html $DEPLOYPATH
    - /bin/cp petrolum.html $DEPLOYPATH
    - /bin/cp automobile.html $DEPLOYPATH
    - /bin/cp telecom.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH